### ISSUE TITLE
Create a task list including estimated times of each task needed to complete Rock 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#1]
This will help me to establish milestones and to plot the timeframe of when we could launch.  Let me know if you have any questions.  Thanks!

**Comment by garand** [comment]
Estimates based on one day equaling 4 hours, and one week equaling 20 hours.
- [x] Setup local enviorment - **1 day**
- [x] Clean up and remove extra code from Uplifted to prepare it for Rock - **2 days**
- [x] Create structure for new front-end styles - **2 days**
- [ ] Write and test front-end styles for child theme - **2 weeks**
- [ ] Create demo content - **2 days**
- [ ] QA theme - **3 days**

This totals 4 weeks (80 hours) of work, which, starting today, puts us at an estimated completion date of January 1st. If met, this would give us the freedom to either launch at the start of the new year, or delay for other marketing reasons. This also assumes most development to be completed by myself, with minor assistance and consultation provided by @chriswallace.

**Comment by imbradmiller** [comment]
It will take you 1 day to setup your local environment? Everything else seems pretty padded. Are you preparing for risks in this estimate?

**Comment by garand** [comment]
Yea, I tried to pad everything a bit so if things go under the estimate it would lend more time to other things that may go over.

As for the local environment, that includes setting up the theme on my computer, setting up an area to deploy updates to for the rest of the team to see, and also configuring a WordPress installation with some test content to use during development.

I'm overestimating most things, with the hopes to have some extra time at the end to either finish early, work on marketing materials, or add some additional features to the framework.

**Comment by imbradmiller** [comment]
Cool. Thanks for the clarification, Anthony.

**Comment by angela-crist** [comment]
@garand Can you let me know where you are in this task list.  I need to create the milestones and I want to ensure it's accurate to where you are now.  Thanks!

**Comment by garand** [comment]
I checked off the checkboxes above with where I'm at.
